
import java.text.*;
import java.util.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        header.setVisible(true); 
        message.setVisible(true);
        profile.setVisible(false);
        schedule.setVisible(false);
        user_profile.setVisible(false); // User Profile 1
        up2.setVisible(false); // User Profile 2
        enrollment.setVisible(false);
        grades.setVisible(false);
        calendar.setVisible(false);
        pword.setVisible(false);
        faculty.setVisible(false);
        graduation.setVisible(false);
    }
    
    public static String getDate() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM d, yyyy"); 
        Date currentDate = new Date();
        String formattedDate = dateFormat.format(currentDate);
        return formattedDate;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pword = new javax.swing.JPanel();
        pwpane = new javax.swing.JPanel();
        newpw = new javax.swing.JLabel();
        changepw = new javax.swing.JLabel();
        newpw_input = new javax.swing.JPasswordField();
        confirmpw = new javax.swing.JLabel();
        confirmpw_input = new javax.swing.JPasswordField();
        oldpw = new javax.swing.JLabel();
        oldpw_input = new javax.swing.JPasswordField();
        clearentry_btn = new javax.swing.JButton();
        changepw_btn = new javax.swing.JButton();
        jlogout7 = new javax.swing.JButton();
        welcomestudent13 = new javax.swing.JLabel();
        cdate4 = new javax.swing.JLabel();
        graduation = new javax.swing.JPanel();
        pwpane2 = new javax.swing.JPanel();
        sy_title2 = new javax.swing.JLabel();
        application_title = new javax.swing.JLabel();
        month_title = new javax.swing.JLabel();
        printout = new javax.swing.JButton();
        month_select = new javax.swing.JComboBox<>();
        sy_input2 = new javax.swing.JTextField();
        jlogout9 = new javax.swing.JButton();
        welcomestudent15 = new javax.swing.JLabel();
        cdate6 = new javax.swing.JLabel();
        faculty = new javax.swing.JPanel();
        facultypane = new javax.swing.JPanel();
        sem_title = new javax.swing.JLabel();
        sy_title = new javax.swing.JLabel();
        faculty_closed = new javax.swing.JLabel();
        sem_input = new javax.swing.JComboBox<>();
        sy_input = new javax.swing.JComboBox<>();
        jlogout8 = new javax.swing.JButton();
        welcomestudent14 = new javax.swing.JLabel();
        cdate5 = new javax.swing.JLabel();
        calendar = new javax.swing.JPanel();
        calendarpane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        noeventdata = new javax.swing.JLabel();
        jlogout6 = new javax.swing.JButton();
        welcomestudent11 = new javax.swing.JLabel();
        cdate3 = new javax.swing.JLabel();
        grades = new javax.swing.JPanel();
        gradespane = new javax.swing.JPanel();
        gradepane = new javax.swing.JScrollPane();
        gradetable2 = new javax.swing.JTable();
        gradepane2 = new javax.swing.JScrollPane();
        gradetable1 = new javax.swing.JTable();
        welcomestudent8 = new javax.swing.JLabel();
        jlogout5 = new javax.swing.JButton();
        enrollment = new javax.swing.JPanel();
        cdate2 = new javax.swing.JLabel();
        enrollpane = new javax.swing.JPanel();
        welcomestudent4 = new javax.swing.JLabel();
        bscs3 = new javax.swing.JLabel();
        bscs4 = new javax.swing.JLabel();
        bscs5 = new javax.swing.JLabel();
        bscs6 = new javax.swing.JLabel();
        bscs7 = new javax.swing.JLabel();
        bscs8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        bscs9 = new javax.swing.JLabel();
        welcomestudent5 = new javax.swing.JLabel();
        jlogout4 = new javax.swing.JButton();
        profile = new javax.swing.JPanel();
        jlogout3 = new javax.swing.JButton();
        welcomestudent6 = new javax.swing.JLabel();
        prevpage_button = new javax.swing.JButton();
        up2 = new javax.swing.JPanel();
        height = new javax.swing.JLabel();
        height_input = new javax.swing.JTextField();
        civ = new javax.swing.JComboBox<>();
        civ_text = new javax.swing.JLabel();
        landline = new javax.swing.JLabel();
        landline_Input = new javax.swing.JTextField();
        cellno = new javax.swing.JLabel();
        cn_input = new javax.swing.JTextField();
        lrn = new javax.swing.JLabel();
        lrn_input = new javax.swing.JTextField();
        fb_text = new javax.swing.JLabel();
        fb_input = new javax.swing.JTextField();
        pwd_text = new javax.swing.JLabel();
        pwd_input = new javax.swing.JComboBox<>();
        indi = new javax.swing.JLabel();
        indi_input = new javax.swing.JComboBox<>();
        weight_input = new javax.swing.JTextField();
        weight = new javax.swing.JLabel();
        user_profile = new javax.swing.JPanel();
        full_name = new javax.swing.JLabel();
        birth_date = new javax.swing.JLabel();
        userprof_title = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        fn_input = new javax.swing.JTextField();
        month_input = new javax.swing.JTextField();
        day_input = new javax.swing.JTextField();
        year_input = new javax.swing.JTextField();
        email_input1 = new javax.swing.JTextField();
        bp_text = new javax.swing.JLabel();
        bp_input = new javax.swing.JTextField();
        ct_text = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        gender_text1 = new javax.swing.JLabel();
        age_input = new javax.swing.JSpinner();
        age_text = new javax.swing.JLabel();
        bp_input1 = new javax.swing.JTextField();
        nextpage_button1 = new javax.swing.JButton();
        schedule = new javax.swing.JPanel();
        cdate = new javax.swing.JLabel();
        sched2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        welcomestudent = new javax.swing.JLabel();
        bscs = new javax.swing.JLabel();
        welcomestudent1 = new javax.swing.JLabel();
        bscs1 = new javax.swing.JLabel();
        jlogout2 = new javax.swing.JButton();
        message = new javax.swing.JPanel();
        cdate1 = new javax.swing.JLabel();
        jlogout1 = new javax.swing.JButton();
        inbox = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        welcomestudent2 = new javax.swing.JLabel();
        bscs2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        welcomestudent3 = new javax.swing.JLabel();
        jtrash_button = new javax.swing.JButton();
        jinbox_button = new javax.swing.JButton();
        jcompose_button = new javax.swing.JButton();
        jdraft_button = new javax.swing.JButton();
        jsent_button = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        TUP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jmenu = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(320, 568));
        getContentPane().setLayout(null);

        pword.setBackground(new java.awt.Color(248, 215, 218));
        pword.setForeground(new java.awt.Color(248, 215, 218));
        pword.setMaximumSize(new java.awt.Dimension(320, 568));
        pword.setMinimumSize(new java.awt.Dimension(320, 568));
        pword.setName(""); // NOI18N
        pword.setLayout(null);

        pwpane.setBackground(new java.awt.Color(255, 255, 255));
        pwpane.setLayout(null);

        newpw.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        newpw.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        newpw.setText("New Password");
        pwpane.add(newpw);
        newpw.setBounds(10, 40, 260, 20);

        changepw.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        changepw.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        changepw.setText("Change Password [Student]");
        pwpane.add(changepw);
        changepw.setBounds(10, 10, 270, 20);

        newpw_input.setText("jPasswordField1");
        pwpane.add(newpw_input);
        newpw_input.setBounds(10, 60, 260, 22);

        confirmpw.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        confirmpw.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        confirmpw.setText("Confirm Password");
        pwpane.add(confirmpw);
        confirmpw.setBounds(10, 90, 260, 20);

        confirmpw_input.setText("jPasswordField1");
        pwpane.add(confirmpw_input);
        confirmpw_input.setBounds(10, 110, 260, 22);

        oldpw.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        oldpw.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        oldpw.setText("Old Password");
        pwpane.add(oldpw);
        oldpw.setBounds(10, 140, 260, 20);

        oldpw_input.setText("jPasswordField1");
        pwpane.add(oldpw_input);
        oldpw_input.setBounds(10, 160, 260, 22);

        clearentry_btn.setBackground(new java.awt.Color(183, 28, 28));
        clearentry_btn.setForeground(new java.awt.Color(255, 255, 255));
        clearentry_btn.setText("Clear Entries");
        clearentry_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearentry_btnActionPerformed(evt);
            }
        });
        pwpane.add(clearentry_btn);
        clearentry_btn.setBounds(160, 200, 110, 23);

        changepw_btn.setBackground(new java.awt.Color(183, 28, 28));
        changepw_btn.setForeground(new java.awt.Color(255, 255, 255));
        changepw_btn.setText("Change Password");
        changepw_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepw_btnActionPerformed(evt);
            }
        });
        pwpane.add(changepw_btn);
        changepw_btn.setBounds(10, 200, 150, 23);

        pword.add(pwpane);
        pwpane.setBounds(10, 70, 290, 240);

        jlogout7.setBackground(new java.awt.Color(242, 0, 0));
        jlogout7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlogout7.setForeground(new java.awt.Color(255, 255, 255));
        jlogout7.setText("Log Out");
        jlogout7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogout7ActionPerformed(evt);
            }
        });
        pword.add(jlogout7);
        jlogout7.setBounds(220, 10, 75, 23);

        welcomestudent13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        welcomestudent13.setText("Welcome");
        pword.add(welcomestudent13);
        welcomestudent13.setBounds(20, 10, 210, 20);

        cdate4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cdate4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cdate4.setText("Current Date: " + Main.getDate());
        pword.add(cdate4);
        cdate4.setBounds(10, 330, 290, 16);

        getContentPane().add(pword);
        pword.setBounds(0, 60, 320, 510);

        graduation.setBackground(new java.awt.Color(248, 215, 218));
        graduation.setForeground(new java.awt.Color(248, 215, 218));
        graduation.setMaximumSize(new java.awt.Dimension(320, 568));
        graduation.setMinimumSize(new java.awt.Dimension(320, 568));
        graduation.setName(""); // NOI18N
        graduation.setLayout(null);

        pwpane2.setBackground(new java.awt.Color(255, 255, 255));
        pwpane2.setLayout(null);

        sy_title2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        sy_title2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sy_title2.setText("School Year");
        pwpane2.add(sy_title2);
        sy_title2.setBounds(10, 40, 260, 20);

        application_title.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        application_title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        application_title.setText("Application for Graduation");
        pwpane2.add(application_title);
        application_title.setBounds(10, 10, 270, 20);

        month_title.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        month_title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        month_title.setText("Month");
        pwpane2.add(month_title);
        month_title.setBounds(10, 90, 260, 20);

        printout.setBackground(new java.awt.Color(183, 28, 28));
        printout.setForeground(new java.awt.Color(255, 255, 255));
        printout.setText("Click Here for the Print Out");
        printout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printoutActionPerformed(evt);
            }
        });
        pwpane2.add(printout);
        printout.setBounds(10, 150, 260, 23);

        month_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        month_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month_selectActionPerformed(evt);
            }
        });
        pwpane2.add(month_select);
        month_select.setBounds(10, 110, 260, 22);

        sy_input2.setText("2324");
        pwpane2.add(sy_input2);
        sy_input2.setBounds(10, 60, 260, 22);

        graduation.add(pwpane2);
        pwpane2.setBounds(10, 70, 290, 190);

        jlogout9.setBackground(new java.awt.Color(242, 0, 0));
        jlogout9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlogout9.setForeground(new java.awt.Color(255, 255, 255));
        jlogout9.setText("Log Out");
        jlogout9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogout9ActionPerformed(evt);
            }
        });
        graduation.add(jlogout9);
        jlogout9.setBounds(220, 10, 75, 23);

        welcomestudent15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        welcomestudent15.setText("Welcome");
        graduation.add(welcomestudent15);
        welcomestudent15.setBounds(20, 10, 210, 20);

        cdate6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cdate6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cdate6.setText("Current Date: " + Main.getDate());
        graduation.add(cdate6);
        cdate6.setBounds(10, 280, 290, 16);

        getContentPane().add(graduation);
        graduation.setBounds(0, 60, 320, 510);

        faculty.setBackground(new java.awt.Color(248, 215, 218));
        faculty.setForeground(new java.awt.Color(248, 215, 218));
        faculty.setMaximumSize(new java.awt.Dimension(320, 568));
        faculty.setMinimumSize(new java.awt.Dimension(320, 568));
        faculty.setName(""); // NOI18N
        faculty.setLayout(null);

        facultypane.setBackground(new java.awt.Color(255, 255, 255));
        facultypane.setLayout(null);

        sem_title.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        sem_title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sem_title.setText("Semester");
        facultypane.add(sem_title);
        sem_title.setBounds(10, 60, 260, 20);

        sy_title.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        sy_title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sy_title.setText("SY");
        facultypane.add(sy_title);
        sy_title.setBounds(10, 10, 270, 20);

        faculty_closed.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        faculty_closed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        faculty_closed.setText("Faculty Evaluation Period is closed.");
        facultypane.add(faculty_closed);
        faculty_closed.setBounds(10, 120, 260, 20);

        sem_input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Third", "Second", "First", "Summer" }));
        facultypane.add(sem_input);
        sem_input.setBounds(10, 80, 260, 22);

        sy_input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2324", "2223", "2122", "2021" }));
        facultypane.add(sy_input);
        sy_input.setBounds(10, 30, 260, 22);

        faculty.add(facultypane);
        facultypane.setBounds(10, 70, 290, 150);

        jlogout8.setBackground(new java.awt.Color(242, 0, 0));
        jlogout8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlogout8.setForeground(new java.awt.Color(255, 255, 255));
        jlogout8.setText("Log Out");
        jlogout8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogout8ActionPerformed(evt);
            }
        });
        faculty.add(jlogout8);
        jlogout8.setBounds(220, 10, 75, 23);

        welcomestudent14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        welcomestudent14.setText("Welcome");
        faculty.add(welcomestudent14);
        welcomestudent14.setBounds(20, 10, 210, 20);

        cdate5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cdate5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cdate5.setText("Current Date: " + Main.getDate());
        faculty.add(cdate5);
        cdate5.setBounds(10, 230, 290, 16);

        getContentPane().add(faculty);
        faculty.setBounds(0, 60, 320, 510);

        calendar.setBackground(new java.awt.Color(248, 215, 218));
        calendar.setForeground(new java.awt.Color(248, 215, 218));
        calendar.setMaximumSize(new java.awt.Dimension(320, 568));
        calendar.setMinimumSize(new java.awt.Dimension(320, 568));
        calendar.setName(""); // NOI18N
        calendar.setLayout(null);

        calendarpane.setBackground(new java.awt.Color(255, 255, 255));
        calendarpane.setLayout(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null,  new Integer(1)},
                { new Integer(2),  new Integer(3),  new Integer(4),  new Integer(5),  new Integer(6),  new Integer(7),  new Integer(8)},
                { new Integer(9),  new Integer(10),  new Integer(11),  new Integer(12),  new Integer(13),  new Integer(14),  new Integer(15)},
                { new Integer(16),  new Integer(17),  new Integer(18),  new Integer(19),  new Integer(20),  new Integer(21),  new Integer(22)},
                { new Integer(23),  new Integer(24),  new Integer(25),  new Integer(26),  new Integer(27),  new Integer(28),  new Integer(29)},
                { new Integer(30), null, null, null, null, null, null}
            },
            new String [] {
                "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(2);
            jTable3.getColumnModel().getColumn(1).setPreferredWidth(2);
            jTable3.getColumnModel().getColumn(2).setPreferredWidth(2);
            jTable3.getColumnModel().getColumn(3).setPreferredWidth(2);
            jTable3.getColumnModel().getColumn(4).setPreferredWidth(2);
            jTable3.getColumnModel().getColumn(5).setPreferredWidth(2);
            jTable3.getColumnModel().getColumn(6).setPreferredWidth(2);
        }

        calendarpane.add(jScrollPane3);
        jScrollPane3.setBounds(10, 10, 270, 150);

        noeventdata.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        noeventdata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noeventdata.setText("No Event Data");
        calendarpane.add(noeventdata);
        noeventdata.setBounds(10, 180, 270, 20);

        calendar.add(calendarpane);
        calendarpane.setBounds(10, 70, 290, 220);

        jlogout6.setBackground(new java.awt.Color(242, 0, 0));
        jlogout6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlogout6.setForeground(new java.awt.Color(255, 255, 255));
        jlogout6.setText("Log Out");
        jlogout6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogout6ActionPerformed(evt);
            }
        });
        calendar.add(jlogout6);
        jlogout6.setBounds(220, 10, 75, 23);

        welcomestudent11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        welcomestudent11.setText("Welcome");
        calendar.add(welcomestudent11);
        welcomestudent11.setBounds(20, 10, 210, 20);

        cdate3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cdate3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cdate3.setText("Current Date: " + Main.getDate());
        calendar.add(cdate3);
        cdate3.setBounds(10, 310, 290, 16);

        getContentPane().add(calendar);
        calendar.setBounds(0, 60, 320, 510);

        grades.setBackground(new java.awt.Color(248, 215, 218));
        grades.setForeground(new java.awt.Color(248, 215, 218));
        grades.setMaximumSize(new java.awt.Dimension(320, 568));
        grades.setMinimumSize(new java.awt.Dimension(320, 568));
        grades.setName(""); // NOI18N
        grades.setLayout(null);

        gradespane.setBackground(new java.awt.Color(255, 255, 255));
        gradespane.setLayout(null);

        gradetable2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        gradetable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Total Units",  new Float(20.0)},
                {"Total Grade Points",  new Float(480.0)},
                {"GWA",  new Float(2.41)}
            },
            new String [] {
                "General Weighted Average", "(GWA)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        gradetable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        gradepane.setViewportView(gradetable2);
        if (gradetable2.getColumnModel().getColumnCount() > 0) {
            gradetable2.getColumnModel().getColumn(0).setPreferredWidth(50);
            gradetable2.getColumnModel().getColumn(1).setPreferredWidth(1);
        }

        gradespane.add(gradepane);
        gradepane.setBounds(10, 140, 270, 90);

        gradetable1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        gradetable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Math",  new Integer(90)},
                {"Science",  new Integer(85)},
                {"History",  new Integer(88)},
                {"English",  new Integer(92)},
                {"Physics",  new Integer(87)}
            },
            new String [] {
                "Subject", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradetable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        gradepane2.setViewportView(gradetable1);
        if (gradetable1.getColumnModel().getColumnCount() > 0) {
            gradetable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            gradetable1.getColumnModel().getColumn(1).setPreferredWidth(1);
        }

        gradespane.add(gradepane2);
        gradepane2.setBounds(10, 10, 270, 120);

        grades.add(gradespane);
        gradespane.setBounds(10, 70, 290, 240);

        welcomestudent8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        welcomestudent8.setText("Welcome");
        grades.add(welcomestudent8);
        welcomestudent8.setBounds(20, 10, 210, 20);

        jlogout5.setBackground(new java.awt.Color(242, 0, 0));
        jlogout5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlogout5.setForeground(new java.awt.Color(255, 255, 255));
        jlogout5.setText("Log Out");
        jlogout5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogout5ActionPerformed(evt);
            }
        });
        grades.add(jlogout5);
        jlogout5.setBounds(220, 10, 75, 23);

        getContentPane().add(grades);
        grades.setBounds(0, 60, 320, 510);

        enrollment.setBackground(new java.awt.Color(248, 215, 218));
        enrollment.setForeground(new java.awt.Color(248, 215, 218));
        enrollment.setMaximumSize(new java.awt.Dimension(320, 568));
        enrollment.setMinimumSize(new java.awt.Dimension(320, 568));
        enrollment.setName(""); // NOI18N
        enrollment.setLayout(null);

        cdate2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cdate2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cdate2.setText("Current Date: " + Main.getDate());
        enrollment.add(cdate2);
        cdate2.setBounds(10, 330, 290, 16);

        enrollpane.setBackground(new java.awt.Color(255, 255, 255));
        enrollpane.setLayout(null);

        welcomestudent4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        welcomestudent4.setText("Student Name: ");
        enrollpane.add(welcomestudent4);
        welcomestudent4.setBounds(10, 10, 210, 16);

        bscs3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bscs3.setForeground(new java.awt.Color(255, 0, 0));
        bscs3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bscs3.setText("Registration is not yet open.");
        enrollpane.add(bscs3);
        bscs3.setBounds(0, 200, 290, 30);

        bscs4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        bscs4.setText("Program:");
        enrollpane.add(bscs4);
        bscs4.setBounds(10, 30, 280, 16);

        bscs5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        bscs5.setText("School Year:");
        enrollpane.add(bscs5);
        bscs5.setBounds(10, 50, 280, 16);

        bscs6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        bscs6.setText("Status:");
        enrollpane.add(bscs6);
        bscs6.setBounds(10, 70, 280, 16);

        bscs7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        bscs7.setText("Student No.:");
        enrollpane.add(bscs7);
        bscs7.setBounds(10, 100, 280, 16);

        bscs8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        bscs8.setText("Year Level:");
        enrollpane.add(bscs8);
        bscs8.setBounds(10, 120, 280, 16);

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select section-", "First", "Second", "Summer" }));
        enrollpane.add(jComboBox1);
        jComboBox1.setBounds(10, 160, 260, 22);

        bscs9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        bscs9.setText("Semester:");
        enrollpane.add(bscs9);
        bscs9.setBounds(10, 140, 280, 16);

        enrollment.add(enrollpane);
        enrollpane.setBounds(10, 70, 290, 250);

        welcomestudent5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        welcomestudent5.setText("Welcome");
        enrollment.add(welcomestudent5);
        welcomestudent5.setBounds(20, 10, 210, 20);

        jlogout4.setBackground(new java.awt.Color(242, 0, 0));
        jlogout4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlogout4.setForeground(new java.awt.Color(255, 255, 255));
        jlogout4.setText("Log Out");
        jlogout4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogout4ActionPerformed(evt);
            }
        });
        enrollment.add(jlogout4);
        jlogout4.setBounds(220, 10, 75, 23);

        getContentPane().add(enrollment);
        enrollment.setBounds(0, 60, 320, 510);

        profile.setBackground(new java.awt.Color(248, 215, 218));
        profile.setForeground(new java.awt.Color(248, 215, 218));
        profile.setMaximumSize(new java.awt.Dimension(320, 568));
        profile.setMinimumSize(new java.awt.Dimension(320, 568));
        profile.setName(""); // NOI18N
        profile.setLayout(null);

        jlogout3.setBackground(new java.awt.Color(242, 0, 0));
        jlogout3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlogout3.setForeground(new java.awt.Color(255, 255, 255));
        jlogout3.setText("Log Out");
        jlogout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogout3ActionPerformed(evt);
            }
        });
        profile.add(jlogout3);
        jlogout3.setBounds(220, 10, 75, 23);

        welcomestudent6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        welcomestudent6.setText("Welcome");
        profile.add(welcomestudent6);
        welcomestudent6.setBounds(10, 6, 210, 30);

        prevpage_button.setBackground(new java.awt.Color(192, 0, 0));
        prevpage_button.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        prevpage_button.setForeground(new java.awt.Color(255, 255, 255));
        prevpage_button.setText("Previous");
        prevpage_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevpage_buttonActionPerformed(evt);
            }
        });
        profile.add(prevpage_button);
        prevpage_button.setBounds(30, 470, 120, 23);

        up2.setBackground(new java.awt.Color(255, 255, 255));
        up2.setLayout(null);

        height.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        height.setText("Height");
        up2.add(height);
        height.setBounds(30, 10, 100, 16);

        height_input.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        height_input.setText("165cm");
        up2.add(height_input);
        height_input.setBounds(30, 30, 90, 22);

        civ.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        civ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Civil Status", "Single", "Married", "Divorced", "Widowed" }));
        up2.add(civ);
        civ.setBounds(30, 80, 200, 22);

        civ_text.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        civ_text.setText("Civil Status:");
        up2.add(civ_text);
        civ_text.setBounds(30, 60, 200, 16);

        landline.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        landline.setText("Landline Number:");
        up2.add(landline);
        landline.setBounds(30, 210, 200, 16);

        landline_Input.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        landline_Input.setText("(800) 588-2300");
        up2.add(landline_Input);
        landline_Input.setBounds(30, 230, 200, 22);

        cellno.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cellno.setText("Cellphone Number:");
        up2.add(cellno);
        cellno.setBounds(30, 160, 200, 16);

        cn_input.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cn_input.setText("09XXXXXXXXX");
        up2.add(cn_input);
        cn_input.setBounds(30, 180, 200, 22);

        lrn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lrn.setText("Learner Reference Number:");
        up2.add(lrn);
        lrn.setBounds(30, 110, 200, 16);

        lrn_input.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lrn_input.setText("LRN12345678910");
        up2.add(lrn_input);
        lrn_input.setBounds(30, 130, 200, 22);

        fb_text.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        fb_text.setText("Facebook Account:");
        up2.add(fb_text);
        fb_text.setBounds(30, 260, 200, 16);

        fb_input.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        fb_input.setText("Juan Dela Cruz");
        up2.add(fb_input);
        fb_input.setBounds(30, 280, 200, 22);

        pwd_text.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pwd_text.setText("PWD (Yes or No):");
        up2.add(pwd_text);
        pwd_text.setBounds(30, 310, 200, 16);

        pwd_input.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pwd_input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Option", "Yes", "No" }));
        up2.add(pwd_input);
        pwd_input.setBounds(30, 330, 200, 22);

        indi.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        indi.setText("Indigenous People (Yes or No):");
        up2.add(indi);
        indi.setBounds(30, 360, 200, 16);

        indi_input.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        indi_input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Option", "Yes", "No" }));
        up2.add(indi_input);
        indi_input.setBounds(30, 380, 200, 22);

        weight_input.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        weight_input.setText("55kg");
        up2.add(weight_input);
        weight_input.setBounds(130, 30, 100, 22);

        weight.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        weight.setText("Weight");
        up2.add(weight);
        weight.setBounds(130, 10, 100, 16);

        profile.add(up2);
        up2.setBounds(10, 50, 290, 410);

        user_profile.setBackground(new java.awt.Color(255, 255, 255));
        user_profile.setLayout(null);

        full_name.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        full_name.setText("Full Name:");
        user_profile.add(full_name);
        full_name.setBounds(30, 50, 210, 16);

        birth_date.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        birth_date.setText("Birth Date:");
        user_profile.add(birth_date);
        birth_date.setBounds(30, 150, 230, 16);

        userprof_title.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        userprof_title.setForeground(new java.awt.Color(139, 0, 0));
        userprof_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userprof_title.setText("User Profile");
        userprof_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user_profile.add(userprof_title);
        userprof_title.setBounds(0, 10, 290, 30);

        email.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        email.setText("Email:");
        user_profile.add(email);
        email.setBounds(30, 100, 200, 16);

        fn_input.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        fn_input.setText("Juan Dela Cruz");
        user_profile.add(fn_input);
        fn_input.setBounds(30, 70, 200, 22);

        month_input.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        month_input.setText("MM");
        user_profile.add(month_input);
        month_input.setBounds(30, 170, 60, 22);

        day_input.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        day_input.setText("DD");
        user_profile.add(day_input);
        day_input.setBounds(100, 170, 60, 22);

        year_input.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        year_input.setText("YYYY");
        user_profile.add(year_input);
        year_input.setBounds(170, 170, 60, 22);

        email_input1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        email_input1.setText("example@tup.edu.ph");
        user_profile.add(email_input1);
        email_input1.setBounds(30, 120, 200, 22);

        bp_text.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        bp_text.setText("Birth Place:");
        user_profile.add(bp_text);
        bp_text.setBounds(30, 200, 200, 16);

        bp_input.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        bp_input.setText("Filipino");
        user_profile.add(bp_input);
        bp_input.setBounds(30, 270, 200, 22);

        ct_text.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ct_text.setText("Citizenship:");
        user_profile.add(ct_text);
        ct_text.setBounds(30, 250, 200, 16);

        gender.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Other" }));
        user_profile.add(gender);
        gender.setBounds(30, 320, 200, 22);

        gender_text1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        gender_text1.setText("Gender");
        user_profile.add(gender_text1);
        gender_text1.setBounds(30, 300, 200, 16);

        age_input.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        user_profile.add(age_input);
        age_input.setBounds(30, 370, 200, 22);

        age_text.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        age_text.setText("Age");
        user_profile.add(age_text);
        age_text.setBounds(30, 350, 40, 16);

        bp_input1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        bp_input1.setText("Quezon City");
        user_profile.add(bp_input1);
        bp_input1.setBounds(30, 220, 200, 22);

        profile.add(user_profile);
        user_profile.setBounds(10, 50, 290, 410);

        nextpage_button1.setBackground(new java.awt.Color(192, 0, 0));
        nextpage_button1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        nextpage_button1.setForeground(new java.awt.Color(255, 255, 255));
        nextpage_button1.setText("Next");
        nextpage_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextpage_button1ActionPerformed(evt);
            }
        });
        profile.add(nextpage_button1);
        nextpage_button1.setBounds(160, 470, 120, 23);

        getContentPane().add(profile);
        profile.setBounds(0, 60, 320, 510);

        schedule.setBackground(new java.awt.Color(248, 215, 218));
        schedule.setForeground(new java.awt.Color(248, 215, 218));
        schedule.setMaximumSize(new java.awt.Dimension(320, 568));
        schedule.setMinimumSize(new java.awt.Dimension(320, 568));
        schedule.setName(""); // NOI18N
        schedule.setLayout(null);

        cdate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cdate.setText("Current Date: " + Main.getDate());
        schedule.add(cdate);
        cdate.setBounds(10, 330, 300, 16);

        sched2.setBackground(new java.awt.Color(255, 255, 255));
        sched2.setLayout(null);

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "CC-303M", "	Methods of Research in Computing",  new Integer(3),  new Integer(0),  new Integer(3), null, "BSCS-3B-M - TH 11:00AM-02:00PM TBA"},
                { new Integer(2), "CS303-M", "Automata Theory and Formal Language",  new Integer(3),  new Integer(0),  new Integer(3), null, "BSCS-3B-M - W 03:00PM-06:00PM TBA"},
                { new Integer(3), "CS321L-M", "Artificial Intelligence, Laboratory",  new Integer(0),  new Integer(1),  new Integer(1), null, "BSCS-3B-M - T 11:00AM-02:00PM TBA"},
                { new Integer(4), "CS322-M", "Artificial Intelligence, Lecture",  new Integer(2),  new Integer(0),  new Integer(2), null, "BSCS-3B-M - T 03:00PM-05:00PM TBA"},
                { new Integer(5), "CS343-M", "Modeling and Simulation",  new Integer(3),  new Integer(0),  new Integer(3), null, "BSCS-3B-M - W 11:00AM-02:00PM TBA"},
                { new Integer(6), "CS361L-M", "Software Engineering 2, Laboratory",  new Integer(0),  new Integer(1),  new Integer(1), null, "BSCS-3B-M - TH 05:00PM-08:00PM TBA"},
                { new Integer(7), "CS362-M", "Software Engineering 2, Lecture",  new Integer(3),  new Integer(0),  new Integer(3), null, "BSCS-3B-M - T 02:30AM-04:30PM TBA"},
                { new Integer(8), "CSE3-M", "CS Professional Elective 3",  new Integer(3),  new Integer(0),  new Integer(3), null, "BSCS-3B-M - W 11:00AM-02:00PM TBA"},
                { new Integer(9), "CSE4-M", "CS Professional Elective 4",  new Integer(3),  new Integer(0),  new Integer(3), null, "BSCS-3B-M - F 07:00AM-10:00AM TBA"}
            },
            new String [] {
                "#", "Subject Code", "Description", "Lec", "Lab", "Units", "Faculty", "Schedule"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        sched2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 270, 180);

        welcomestudent.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        welcomestudent.setText("SY: 2023-2024");
        sched2.add(welcomestudent);
        welcomestudent.setBounds(10, 10, 210, 16);

        bscs.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        bscs.setText("Term/Sem: 2nd");
        sched2.add(bscs);
        bscs.setBounds(10, 30, 280, 16);

        schedule.add(sched2);
        sched2.setBounds(10, 70, 290, 250);

        welcomestudent1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        welcomestudent1.setText("Welcome Student!");
        schedule.add(welcomestudent1);
        welcomestudent1.setBounds(10, 20, 210, 16);

        bscs1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        bscs1.setText("Bachelor of Science in Computer Science");
        schedule.add(bscs1);
        bscs1.setBounds(10, 40, 310, 16);

        jlogout2.setBackground(new java.awt.Color(242, 0, 0));
        jlogout2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlogout2.setForeground(new java.awt.Color(255, 255, 255));
        jlogout2.setText("Log Out");
        jlogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogout2ActionPerformed(evt);
            }
        });
        schedule.add(jlogout2);
        jlogout2.setBounds(220, 10, 75, 23);

        getContentPane().add(schedule);
        schedule.setBounds(0, 60, 320, 510);

        message.setBackground(new java.awt.Color(248, 215, 218));
        message.setForeground(new java.awt.Color(248, 215, 218));
        message.setMaximumSize(new java.awt.Dimension(320, 568));
        message.setMinimumSize(new java.awt.Dimension(320, 568));
        message.setName(""); // NOI18N
        message.setLayout(null);

        cdate1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cdate1.setText("Current Date: " + Main.getDate());
        message.add(cdate1);
        cdate1.setBounds(10, 330, 300, 16);

        jlogout1.setBackground(new java.awt.Color(242, 0, 0));
        jlogout1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlogout1.setForeground(new java.awt.Color(255, 255, 255));
        jlogout1.setText("Log Out");
        jlogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogout1ActionPerformed(evt);
            }
        });
        message.add(jlogout1);
        jlogout1.setBounds(220, 10, 75, 23);

        inbox.setBackground(new java.awt.Color(255, 255, 255));
        inbox.setLayout(null);

        jTable2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "User Type", "Subject", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
        }

        inbox.add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 270, 30);

        welcomestudent2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        welcomestudent2.setText("Welcome, Student!");
        inbox.add(welcomestudent2);
        welcomestudent2.setBounds(10, 10, 210, 16);

        bscs2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        bscs2.setText("Inbox");
        inbox.add(bscs2);
        bscs2.setBounds(10, 30, 280, 16);

        jButton1.setBackground(new java.awt.Color(242, 0, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        inbox.add(jButton1);
        jButton1.setBounds(10, 100, 70, 21);

        message.add(inbox);
        inbox.setBounds(10, 190, 290, 130);

        welcomestudent3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        welcomestudent3.setText("Welcome");
        message.add(welcomestudent3);
        welcomestudent3.setBounds(20, 10, 210, 20);

        jtrash_button.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtrash_button.setText("Trash");
        jtrash_button.setActionCommand("");
        jtrash_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtrash_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        message.add(jtrash_button);
        jtrash_button.setBounds(10, 140, 290, 23);

        jinbox_button.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jinbox_button.setText("Inbox");
        jinbox_button.setActionCommand("");
        jinbox_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jinbox_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jinbox_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinbox_buttonActionPerformed(evt);
            }
        });
        message.add(jinbox_button);
        jinbox_button.setBounds(10, 60, 290, 23);

        jcompose_button.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jcompose_button.setText("Compose");
        jcompose_button.setActionCommand("");
        jcompose_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcompose_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        message.add(jcompose_button);
        jcompose_button.setBounds(10, 80, 290, 23);

        jdraft_button.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jdraft_button.setText("Draft");
        jdraft_button.setActionCommand("");
        jdraft_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jdraft_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jdraft_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdraft_buttonActionPerformed(evt);
            }
        });
        message.add(jdraft_button);
        jdraft_button.setBounds(10, 100, 290, 23);

        jsent_button.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jsent_button.setText("Sent");
        jsent_button.setActionCommand("");
        jsent_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jsent_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jsent_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsent_buttonActionPerformed(evt);
            }
        });
        message.add(jsent_button);
        jsent_button.setBounds(10, 120, 290, 23);

        getContentPane().add(message);
        message.setBounds(0, 60, 320, 510);

        header.setBackground(new java.awt.Color(242, 0, 0));
        header.setLayout(null);

        TUP.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        TUP.setForeground(new java.awt.Color(255, 255, 255));
        TUP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TUP.setText("TECHNOLOGICAL UNIVERSITY OF THE PHILIPPINES");
        header.add(TUP);
        TUP.setBounds(10, 10, 310, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        header.add(jLabel2);
        jLabel2.setBounds(0, 10, 46, 48);

        jmenu.setBackground(new java.awt.Color(242, 0, 0));
        jmenu.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jmenu.setForeground(new java.awt.Color(255, 255, 255));
        jmenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Message", "Profile", "Enrollment", "Schedule", "Grades", "Calendar", "Password", "Faculty Evaluation", "Application For Graduation" }));
        jmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuActionPerformed(evt);
            }
        });
        header.add(jmenu);
        jmenu.setBounds(50, 30, 230, 22);

        getContentPane().add(header);
        header.setBounds(0, 0, 320, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsent_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsent_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsent_buttonActionPerformed

    private void jdraft_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdraft_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdraft_buttonActionPerformed

    private void jinbox_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinbox_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jinbox_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jlogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogout1ActionPerformed
        Login f = new Login();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jlogout1ActionPerformed

    private void jmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuActionPerformed
        JComboBox comboBox = (JComboBox) evt.getSource(); 
        String selectedItem = (String) comboBox.getSelectedItem(); 
        
        switch (selectedItem) {
            case "Message" -> {
                header.setVisible(true);
                message.setVisible(true);
                schedule.setVisible(false);
                profile.setVisible(false);
                user_profile.setVisible(false); // User Profile 1
                up2.setVisible(false); // User Profile 2
                enrollment.setVisible(false);
                grades.setVisible(false);
                calendar.setVisible(false);
                pword.setVisible(false);
                faculty.setVisible(false);
                graduation.setVisible(false);
            }
            case "Schedule" -> {
                header.setVisible(true);
                message.setVisible(false);
                schedule.setVisible(true);
                profile.setVisible(false);
                user_profile.setVisible(false); // User Profile 1
                up2.setVisible(false); // User Profile 2
                enrollment.setVisible(false);
                grades.setVisible(false);
                calendar.setVisible(false);
                pword.setVisible(false);
                faculty.setVisible(false);
                graduation.setVisible(false);
            }
            case "Profile" -> {
                header.setVisible(true);
                message.setVisible(false);
                schedule.setVisible(false);
                profile.setVisible(true);
                user_profile.setVisible(true); // User Profile 1
                up2.setVisible(false); // User Profile 2
                enrollment.setVisible(false);
                grades.setVisible(false);
                calendar.setVisible(false);
                pword.setVisible(false);
                faculty.setVisible(false);
                graduation.setVisible(false);
            }
            case "Enrollment" -> {
                header.setVisible(true);
                message.setVisible(false);
                schedule.setVisible(false);
                profile.setVisible(false);
                user_profile.setVisible(false); // User Profile 1
                up2.setVisible(false); // User Profile 2
                enrollment.setVisible(true);
                grades.setVisible(false);
                calendar.setVisible(false);
                pword.setVisible(false);
                faculty.setVisible(false);
                graduation.setVisible(false);
            }
            case "Grades" -> {
                header.setVisible(true);
                message.setVisible(false);
                schedule.setVisible(false);
                profile.setVisible(false);
                user_profile.setVisible(false); // User Profile 1
                up2.setVisible(false);  // User Profile 2
                enrollment.setVisible(false);
                grades.setVisible(true);
                calendar.setVisible(false);
                pword.setVisible(false);
                faculty.setVisible(false);
                graduation.setVisible(false);
            }
            case "Calendar" -> {
                header.setVisible(true);
                message.setVisible(false);
                schedule.setVisible(false);
                profile.setVisible(false);
                user_profile.setVisible(false); // User Profile 1
                up2.setVisible(false);  // User Profile 2
                enrollment.setVisible(false);
                grades.setVisible(false);
                calendar.setVisible(true);
                pword.setVisible(false);
                faculty.setVisible(false);
                graduation.setVisible(false);
            }
            case "Password" -> {
                header.setVisible(true);
                message.setVisible(false);
                schedule.setVisible(false);
                profile.setVisible(false);
                user_profile.setVisible(false); // User Profile 1
                up2.setVisible(false);  // User Profile 2
                enrollment.setVisible(false);
                grades.setVisible(false);
                calendar.setVisible(false);
                pword.setVisible(true);
                faculty.setVisible(false);
                graduation.setVisible(false);
            }
            case "Faculty Evaluation" -> {
                header.setVisible(true);
                message.setVisible(false);
                schedule.setVisible(false);
                profile.setVisible(false);
                user_profile.setVisible(false); // User Profile 1
                up2.setVisible(false);  // User Profile 2
                enrollment.setVisible(false);
                grades.setVisible(false);
                calendar.setVisible(false);
                pword.setVisible(false);
                faculty.setVisible(true);
                graduation.setVisible(false);
            }
            case "Application For Graduation" -> {
                header.setVisible(true);
                message.setVisible(false);
                schedule.setVisible(false);
                profile.setVisible(false);
                user_profile.setVisible(false); // User Profile 1
                up2.setVisible(false);  // User Profile 2
                enrollment.setVisible(false);
                grades.setVisible(false);
                calendar.setVisible(false);
                pword.setVisible(false);
                faculty.setVisible(false);
                graduation.setVisible(true);
            }
            default -> System.out.println("Unexpected item selected: " + selectedItem);
        }
    }//GEN-LAST:event_jmenuActionPerformed

    private void jlogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogout2ActionPerformed
        Login f = new Login();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jlogout2ActionPerformed

    private void jlogout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogout3ActionPerformed
        Login f = new Login();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jlogout3ActionPerformed

    private void prevpage_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevpage_buttonActionPerformed
        header.setVisible(true);
        message.setVisible(false);
        schedule.setVisible(false);
        profile.setVisible(true);
        user_profile.setVisible(true);
        up2.setVisible(false);
        enrollment.setVisible(false);
        grades.setVisible(false);
        calendar.setVisible(false);
        pword.setVisible(false);
        faculty.setVisible(false);
        graduation.setVisible(false);
    }//GEN-LAST:event_prevpage_buttonActionPerformed

    private void nextpage_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextpage_button1ActionPerformed
        header.setVisible(true);
        message.setVisible(false);
        schedule.setVisible(false);
        profile.setVisible(true);
        user_profile.setVisible(false);
        up2.setVisible(true);
        enrollment.setVisible(false);
        grades.setVisible(false);
        calendar.setVisible(false);
        pword.setVisible(false);
        faculty.setVisible(false);
        graduation.setVisible(false);
    }//GEN-LAST:event_nextpage_button1ActionPerformed

    private void jlogout4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogout4ActionPerformed
        Login f = new Login();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jlogout4ActionPerformed

    private void jlogout5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogout5ActionPerformed
        Login f = new Login();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jlogout5ActionPerformed

    private void jlogout6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogout6ActionPerformed
        Login f = new Login();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jlogout6ActionPerformed

    private void jlogout7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogout7ActionPerformed
        Login f = new Login();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jlogout7ActionPerformed

    private void clearentry_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearentry_btnActionPerformed
        // To clear entries
    }//GEN-LAST:event_clearentry_btnActionPerformed

    private void changepw_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepw_btnActionPerformed
        JOptionPane.showMessageDialog(null, "Your password has been changed.");
    }//GEN-LAST:event_changepw_btnActionPerformed

    private void jlogout8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogout8ActionPerformed
        Login f = new Login();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jlogout8ActionPerformed

    private void printoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printoutActionPerformed
        JOptionPane.showMessageDialog(null, "Your form has been printed.");
    }//GEN-LAST:event_printoutActionPerformed

    private void jlogout9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogout9ActionPerformed
        Login f = new Login();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jlogout9ActionPerformed

    private void month_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month_selectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_month_selectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TUP;
    private javax.swing.JSpinner age_input;
    private javax.swing.JLabel age_text;
    private javax.swing.JLabel application_title;
    private javax.swing.JLabel birth_date;
    private javax.swing.JTextField bp_input;
    private javax.swing.JTextField bp_input1;
    private javax.swing.JLabel bp_text;
    private javax.swing.JLabel bscs;
    private javax.swing.JLabel bscs1;
    private javax.swing.JLabel bscs2;
    private javax.swing.JLabel bscs3;
    private javax.swing.JLabel bscs4;
    private javax.swing.JLabel bscs5;
    private javax.swing.JLabel bscs6;
    private javax.swing.JLabel bscs7;
    private javax.swing.JLabel bscs8;
    private javax.swing.JLabel bscs9;
    private javax.swing.JPanel calendar;
    private javax.swing.JPanel calendarpane;
    private javax.swing.JLabel cdate;
    private javax.swing.JLabel cdate1;
    private javax.swing.JLabel cdate2;
    private javax.swing.JLabel cdate3;
    private javax.swing.JLabel cdate4;
    private javax.swing.JLabel cdate5;
    private javax.swing.JLabel cdate6;
    private javax.swing.JLabel cellno;
    private javax.swing.JLabel changepw;
    private javax.swing.JButton changepw_btn;
    private javax.swing.JComboBox<String> civ;
    private javax.swing.JLabel civ_text;
    private javax.swing.JButton clearentry_btn;
    private javax.swing.JTextField cn_input;
    private javax.swing.JLabel confirmpw;
    private javax.swing.JPasswordField confirmpw_input;
    private javax.swing.JLabel ct_text;
    private javax.swing.JTextField day_input;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email_input1;
    private javax.swing.JPanel enrollment;
    private javax.swing.JPanel enrollpane;
    private javax.swing.JPanel faculty;
    private javax.swing.JLabel faculty_closed;
    private javax.swing.JPanel facultypane;
    private javax.swing.JTextField fb_input;
    private javax.swing.JLabel fb_text;
    private javax.swing.JTextField fn_input;
    private javax.swing.JLabel full_name;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel gender_text1;
    private javax.swing.JScrollPane gradepane;
    private javax.swing.JScrollPane gradepane2;
    private javax.swing.JPanel grades;
    private javax.swing.JPanel gradespane;
    private javax.swing.JTable gradetable1;
    private javax.swing.JTable gradetable2;
    private javax.swing.JPanel graduation;
    private javax.swing.JPanel header;
    private javax.swing.JLabel height;
    private javax.swing.JTextField height_input;
    private javax.swing.JPanel inbox;
    private javax.swing.JLabel indi;
    private javax.swing.JComboBox<String> indi_input;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton jcompose_button;
    private javax.swing.JButton jdraft_button;
    private javax.swing.JButton jinbox_button;
    private javax.swing.JButton jlogout1;
    private javax.swing.JButton jlogout2;
    private javax.swing.JButton jlogout3;
    private javax.swing.JButton jlogout4;
    private javax.swing.JButton jlogout5;
    private javax.swing.JButton jlogout6;
    private javax.swing.JButton jlogout7;
    private javax.swing.JButton jlogout8;
    private javax.swing.JButton jlogout9;
    private javax.swing.JComboBox<String> jmenu;
    private javax.swing.JButton jsent_button;
    private javax.swing.JButton jtrash_button;
    private javax.swing.JLabel landline;
    private javax.swing.JTextField landline_Input;
    private javax.swing.JLabel lrn;
    private javax.swing.JTextField lrn_input;
    private javax.swing.JPanel message;
    private javax.swing.JTextField month_input;
    private javax.swing.JComboBox<String> month_select;
    private javax.swing.JLabel month_title;
    private javax.swing.JLabel newpw;
    private javax.swing.JPasswordField newpw_input;
    private javax.swing.JButton nextpage_button1;
    private javax.swing.JLabel noeventdata;
    private javax.swing.JLabel oldpw;
    private javax.swing.JPasswordField oldpw_input;
    private javax.swing.JButton prevpage_button;
    private javax.swing.JButton printout;
    private javax.swing.JPanel profile;
    private javax.swing.JComboBox<String> pwd_input;
    private javax.swing.JLabel pwd_text;
    private javax.swing.JPanel pword;
    private javax.swing.JPanel pwpane;
    private javax.swing.JPanel pwpane2;
    private javax.swing.JPanel sched2;
    private javax.swing.JPanel schedule;
    private javax.swing.JComboBox<String> sem_input;
    private javax.swing.JLabel sem_title;
    private javax.swing.JComboBox<String> sy_input;
    private javax.swing.JTextField sy_input2;
    private javax.swing.JLabel sy_title;
    private javax.swing.JLabel sy_title2;
    private javax.swing.JPanel up2;
    private javax.swing.JPanel user_profile;
    private javax.swing.JLabel userprof_title;
    private javax.swing.JLabel weight;
    private javax.swing.JTextField weight_input;
    private javax.swing.JLabel welcomestudent;
    private javax.swing.JLabel welcomestudent1;
    private javax.swing.JLabel welcomestudent11;
    private javax.swing.JLabel welcomestudent13;
    private javax.swing.JLabel welcomestudent14;
    private javax.swing.JLabel welcomestudent15;
    private javax.swing.JLabel welcomestudent2;
    private javax.swing.JLabel welcomestudent3;
    private javax.swing.JLabel welcomestudent4;
    private javax.swing.JLabel welcomestudent5;
    private javax.swing.JLabel welcomestudent6;
    private javax.swing.JLabel welcomestudent8;
    private javax.swing.JTextField year_input;
    // End of variables declaration//GEN-END:variables
}
